Using Bootstrap request for review
Joecleverman/using-bootstrap pull request #1
Opened 2020-02-05 19:19 UTC by Joecleverman

I complete the using bootstrap project (mobile-first for responsive) I would like a TSS to review it, please.

2020-02-05 23:45 UTC, MauricioRobayo requested changes
Hi,

Great start, the project is looking good and you are making very nice use of Bootstrap, but need to fix some issues:

* [ ] Fix [HTML validation errors](https://validator.w3.org/nu/?doc=https%3A%2F%2Frawcdn.githack.com%2FJoecleverman%2Fusing-bootstrap%2F5b4bcf5e3104fe8e7264f2548eb3711249421d81%2Findex.html).
* [ ] Enable Stickler on this repository.
* [ ] Do not make any changes in config files - they represent style guidelines that you share with your team - which is a group of all Microverse students. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/linter_config.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/))
* [ ] Verify the path to the images you are using, they are not loading - although this might be a Newsweek issue since I verified on the original page and the images are not loading there either.

#### Footer

* [x] It contains social media icons ([link to page](https://www.newsweek.com/)).

Please update this PR and request a new code review 😊.

Status: __Request changes__.

__[OPTIONAL]__

* [ ] You could of the [`<main>` tag](https://www.w3schools.com/tags/tag_main.asp) for the dominant content of the `<body>` of a document.

2020-02-05 23:45 UTC, MauricioRobayo commented on .stickler.yml
> +    fixer: true
Use the provided [`.stickler.yml` file](https://github.com/microverseinc/linters-config/blob/master/css/.stickler.yml), you should not make any changes to this file.

2020-02-06 17:02 UTC, Joecleverman commented
I solve the issues raised by the TSS, but for the HTML validation there is a lot of warnings related to SVG there is nothing I can do about that and some warnings related to h2, h6 I'm using bootstrap there is no need for h2....h6. I do not see what I can do to solve it.

2020-02-06 18:12 UTC, mosesogwo requested changes
### Hi @Joecleverman, Nice work.:+1: Here are some changes we need to make  in order to move forward:
1. The body of the page is not centered. We have more whitespace to the right than on the left.

2. The navbar breaks before the medium screen breakpoint. Let's fix this.
![image](https://user-images.githubusercontent.com/46611870/73964385-5b67f500-4912-11ea-9b0a-7437a526d3ef.png)

3. Let us remove the **US** label above the picture in this section:
![image](https://user-images.githubusercontent.com/46611870/73964424-7175b580-4912-11ea-944f-9fb892070dcf.png)

4. Please use appropriately sized images in the **Latest News section**. Consider saving the images directly from that section on the original page.

5. Reduce the margin between image & text in the **More Stories** section.

6. Check the image-text ratio in these columns under the **US, World, Business ...** sections. Use appropriately sized images.
![image](https://user-images.githubusercontent.com/46611870/73964649-e517c280-4912-11ea-827a-ab9505a6e5ea.png)

7.Let's remove the bg color in the **Culture** section.
![image](https://user-images.githubusercontent.com/46611870/73964784-27d99a80-4913-11ea-86a6-349356f6a6ea.png)

8. On small screens, the alignment for **Latest News** section is **Image to the left, text to the right,** not text below image.

9. On small screens, remove left margin from social media icons section within the footer.

10. Adjust the font-sizes and style, especially for our article titles to look more like the original.

11. Find workarounds for the markup validation errors. You can add hidden headers to fix the header warnings. They have to be fixed.

_**Kindly make these changes and submit another code review request.**_

**Cheers:smile:**

### Status: Changes requested.

2020-02-11 14:47 UTC, Joecleverman commented
All Issue solved. This is a new pull request for a new code review.

2020-02-11 15:32 UTC, nikasulo requested changes
# Under Review By Tolulope Olusakin(TSE)
Please check on this in a few minutes for some feedback

2020-02-11 16:37 UTC, nikasulo requested changes
# Really great job @Joecleverman :clap: 
Your project is coming together very nicely :+1: Please consider the few comments I've left below

#### Responsiveness
Your project could use a little more responsiveness, please look a little more closely at the sizes of elements, padding of sections, margins, and general element positionings. These are very key as they will affect the look, feel, and more importantly the usability of your sites. I went ahead to attach a few images of areas where I noticed issues with responsiveness, however, please do a full scan of your page just in case I missed or left something out.

The following are some of the responsive issues I've run into:
![screenshot](https://images2.imgbox.com/6d/e8/rSTBVVcD_o.png)
![screenshot](https://images2.imgbox.com/88/fe/a4cqez4K_o.png)

Please look into the unnecessary space above/ below sections and take a closer look at your navigation bar

#### Missing social icons
Please take consider the following screenshot, you may find that your social media icons are missing in the footer of your project. Please make the necessary adjustments and request another review!
![screenshot](https://images2.imgbox.com/05/e5/FTU44xlB_o.png)

### Summary
There are some sections with too much space above/below them, your footer is missing social media icons and your navigation's styling breaks on mobile. Please attend to these and request another review! All the best :smile: :rocket: 

### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

2020-02-11 17:09 UTC, Joecleverman commented
I'm sorry Oluwadamilareolusakin you just reviewed an old version. I forgot to change the live link. These errors are not in the new version.

2020-02-11 19:40 UTC, mosesogwo requested changes
**Hi @Joecleverman, good work:+1:, but some changes are still required.**

1. The spacing between lines in the title and below the title of the **Featured Stories** section is too much. Let us close up the gap a little.

![image](https://user-images.githubusercontent.com/46611870/74270876-39a0b080-4d0c-11ea-97fc-faf36079bbb1.png)



2. Also, in the **More Stories** section, space below the title is too much and text beyond the image height should wrap below the image. Also, remove left margin/padding from the section title.

![image](https://user-images.githubusercontent.com/46611870/74270786-12e27a00-4d0c-11ea-8b4e-bb3ddaa5dbc6.png)

3. **Editor's Picks Section:** reduce spacing between lines in the article title and spacing after article title.

![image](https://user-images.githubusercontent.com/46611870/74271022-7f5d7900-4d0c-11ea-976f-b390ee1116c0.png)

4. **On medium screens:** Compare left margin of the Opinion Section and Latest news section with original.

5. **On medium screens, Latest News section:** Article titles should be aligned with the top of the image. Also add some margin below the section title.
![image](https://user-images.githubusercontent.com/46611870/74271333-03176580-4d0d-11ea-8283-6cefbafdf86c.png)

6. Check the copyright element in the footer section, on medium screens.

![image](https://user-images.githubusercontent.com/46611870/74271443-32c66d80-4d0d-11ea-9391-a63c45409de7.png)


7.  On small screens, reduce the left and right margins of the sections beginning from **In the magazine** to the section just before the footer. Compare with the original page to see the difference.

8. On small screens, Images in the **More Stories** section appear really small when compared with the original.

![image](https://user-images.githubusercontent.com/46611870/74271813-d283fb80-4d0d-11ea-9b34-97049949d0f2.png

9. Check spacing above the title of **In the magazine** section

![image](https://user-images.githubusercontent.com/46611870/74272292-addc5380-4d0e-11ea-9841-e6349fe3ac79.png)


_**Let us fix these and submit another code review request.**_

**Good luck:stars:**

2020-02-13 15:43 UTC, Joecleverman commented
complete all changed requested.

2020-02-13 17:25 UTC, nikasulo approved these changes
Congratulations @Joecleverman! :clap: 
Exceptional work building this and incorporating all the requested changes. You may merge and keep moving forward :+1: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

2020-02-13 17:47 UTC, merged